In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a Numpy array from baseball: np_baseball

np_baseball=np.array(baseball)
# Print out type of np_baseball
y=type(np_baseball)
print(y)

<class 'numpy.ndarray'>


In [2]:
# height is available as a regular list
height = [74, 74, 72 , 75, 75, 73]

# Import numpy
import numpy as np

# Create a Numpy array from height: np_height
np_height=np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m=np_height*0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 75 75 73]
[1.8796 1.8796 1.8288 1.905  1.905  1.8542]


In [3]:
# height and weight are available as a regular lists
weight = [180, 215, 210, 210, 188, 176]

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg=np.array(weight)*0.453592

# Calculate the BMI: bmi
bmi=np_weight_kg/np_height_m**2

# Print out bmi
print(bmi)

[23.11037639 27.60406069 28.48080465 26.24790956 23.49812856 23.22014357]


In [4]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light=bmi<21

# Print out light
print(light)


# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False False False False False]
[]


In [5]:
# np.array([4, 3, 0]) + np.array([0, 2, 2])

In [6]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight = np.array(weight)
np_height = np.array(height)

# Print out the weight at index 50
print(np_weight[5])

# Print out sub-array of np_height: index 100 up to and including index 110
print(np_height[1:11])

176
[74 72 75 75 73]


In [7]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [8]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [ ]:
# baseball is available as a regular list of lists
baseball = [[74, 180], [74, 215], [72, 210], [72, 210], [73, 188], [69, 176], [69, 209]]

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[50,:])

# Select the entire second column of np_baseball: np_weight
np_weight=np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[:124])

In [ ]:
# baseball is available as a regular list of lists
# update is available as 2D Numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and update
print(np_baseball+update)

# Create Numpy array: conversion
conversion=[0.0254,0.453592,1]

# Print out product of np_baseball and conversion
print(np_baseball*conversion)

In [ ]:
# np_baseball is available

# Import numpy
import numpy as np
print(np_baseball.shape)
# Create np_height from np_baseball
np_height=np.array(np_baseball[:,0])

print(np_height)
# Print out the mean of np_height
print(np.mean(np_height))

# Print out the median of np_height
print(np.median(np_height))

In [ ]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

In [ ]:
# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions=np.array(positions)
np_heights=np.array(heights)


# Heights of the goalkeepers: gk_heights
gk_heights=np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights=np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))