In [1]:
# Numeric vector: 1 up to 10
my_vector <- 1:10 

# Numeric matrix: 1 up to 9
my_matrix <- matrix(1:9, ncol = 3)

# Factor of sizes
my_factor <- factor(c("M","S","L","L","M"), ordered = TRUE, levels = c("S","M","L"))

# Construct my_list with these different elements
my_list = list(my_vector,my_matrix,my_factor)

In [2]:
my_list

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
[1] M S L L M
Levels: S < M < L

In [3]:
# Numeric vector: 1 up to 10
my_vector <- 1:10 

# Numeric matrix: 1 up to 9
my_matrix <- matrix(1:9, ncol = 3)

# Factor of sizes
my_factor <- factor(c("M","S","L","L","M"), ordered = TRUE, levels = c("S","M","L"))

# List containing vector, matrix and factor
my_list <- list(my_vector, my_matrix, my_factor)

# Construct my_super_list with the four data structures above
my_super_list = list(my_vector,my_matrix,my_factor,my_list)
my_super_list
# Display structure of my_super_list
str(my_super_list)

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
[1] M S L L M
Levels: S < M < L

[[4]]
[[4]][[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[4]][[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[4]][[3]]
[1] M S L L M
Levels: S < M < L

List of 4
 $ : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
 $ : Ord.factor w/ 3 levels "S"<"M"<"L": 2 1 3 3 2
 $ :List of 3
  ..$ : int [1:10] 1 2 3 4 5 6 7 8 9 10
  ..$ : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
  ..$ : Ord.factor w/ 3 levels "S"<"M"<"L": 2 1 3 3 2


In [4]:
# Numeric vector: 1 up to 10
my_vector <- 1:10 

# Numeric matrix: 1 up to 9
my_matrix <- matrix(1:9, ncol = 3)

# Factor of sizes
my_factor <- factor(c("M","S","L","L","M"), ordered = TRUE, levels = c("S","M","L"))

# Construct my_list with these different elements
my_list <- list(vec=my_vector, mat=my_matrix, fac=my_factor)


# Print my_list to the console
my_list

$vec
 [1]  1  2  3  4  5  6  7  8  9 10

$mat
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$fac
[1] M S L L M
Levels: S < M < L

In [5]:
# Create actors and reviews
actors_vector <- c("Jack Nicholson","Shelley Duvall","Danny Lloyd","Scatman Crothers","Barry Nelson")
reviews_factor <- factor(c("Good", "OK", "Good", "Perfect", "Bad", "Perfect", "Good"), 
                  ordered = TRUE, levels = c("Bad", "OK", "Good", "Perfect"))

# Create shining_list
shining_list = list(title="The Shining", actors=actors_vector, reviews=reviews_factor)
shining_list

$title
[1] "The Shining"

$actors
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

$reviews
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect

In [ ]:
# Create the list lst
top
prop

lst <- list(top[5],prop[,4])
lst

# Create the list skills
skills = list(topics=top,context=cont,properties=prop,list_info=lst)
skills
# Display the structure of skills
str(skills)

In [6]:
# shining_list is already defined in the workspace
shining_list
# Actors from shining_list: act
act = shining_list$actors

# List containing title and reviews from shining_list: sublist
sublist = list(shining_list$title, shining_list$reviews)

# Display structure of sublist
str(sublist)

$title
[1] "The Shining"

$actors
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

$reviews
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect

List of 2
 $ : chr "The Shining"
 $ : Ord.factor w/ 4 levels "Bad"<"OK"<"Good"<..: 3 2 3 4 1 4 3


In [8]:
# shining_list is already defined in the workspace

# Select the last actor: last_actor
last_actor = shining_list$actors[[5]]
last_actor
# Select the second review: second_review
second_review = shining_list$reviews[[2]]
second_review

[1] "Barry Nelson"

[1] OK
Levels: Bad < OK < Good < Perfect

In [9]:
# A and C are correct

In [10]:
# shining_list is already defined in the workspace
shining_list
# Add the release year to shining_list
shining_list$year <- 1980

# Add the director to shining_list
shining_list$director <- "Stanley Kubrick"

# Inspect the structure of shining_list
str(shining_list)

$title
[1] "The Shining"

$actors
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

$reviews
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect

List of 5
 $ title   : chr "The Shining"
 $ actors  : chr [1:5] "Jack Nicholson" "Shelley Duvall" "Danny Lloyd" "Scatman Crothers" ...
 $ reviews : Ord.factor w/ 4 levels "Bad"<"OK"<"Good"<..: 3 2 3 4 1 4 3
 $ year    : num 1980
 $ director: chr "Stanley Kubrick"


In [11]:
# shining_list is already defined in the workspace

# Add both the year and director to shining_list: shining_list_ext
shining_list_ext <- c(shining_list,list(year=1980,director="Stanley Kubrick"))
shining_list_ext
# Have a look at the structure of shining_list_ext
str(shining_list_ext)

$title
[1] "The Shining"

$actors
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

$reviews
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect

$year
[1] 1980

$director
[1] "Stanley Kubrick"

$year
[1] 1980

$director
[1] "Stanley Kubrick"

List of 7
 $ title   : chr "The Shining"
 $ actors  : chr [1:5] "Jack Nicholson" "Shelley Duvall" "Danny Lloyd" "Scatman Crothers" ...
 $ reviews : Ord.factor w/ 4 levels "Bad"<"OK"<"Good"<..: 3 2 3 4 1 4 3
 $ year    : num 1980
 $ director: chr "Stanley Kubrick"
 $ year    : num 1980
 $ director: chr "Stanley Kubrick"


In [ ]:
# Create the list key_skills

key_skills = list(skills$topics[2],skills$context[2],skills$list_info[[2]][4])