In [1]:
# Star Wars box office in millions (!)
box <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)

# Create star_wars_matrix
star_wars_matrix = matrix(box, byrow=TRUE, nrow = 3, ncol=2)
star_wars_matrix

[,1]    [,2] 
[1,] 460.998 314.4
[2,] 290.475 247.9
[3,] 309.306 165.8

In [2]:
# Star Wars box office in millions (!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Create star_wars_matrix
star_wars_matrix=rbind(new_hope,empire_strikes,return_jedi)
star_wars_matrix

[,1]    [,2] 
new_hope       460.998 314.4
empire_strikes 290.475 247.9
return_jedi    309.306 165.8

In [3]:
# Star Wars box office in millions (!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)
star_wars_matrix <- rbind(new_hope, empire_strikes, return_jedi)

# Name the columns and rows of star_wars_matrix
colnames(star_wars_matrix) = c("US", "non-US")
rownames(star_wars_matrix) = c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")
star_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

In [4]:
# Only D is valid syntax that leads to the correct result.

In [5]:
# Star Wars box office in millions (!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)
star_wars_matrix <- rbind(new_hope, empire_strikes, return_jedi)
colnames(star_wars_matrix) <- c("US", "non-US")
rownames(star_wars_matrix) <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

# Calculate the worldwide box office: worldwide_vector
worldwide_vector = rowSums(star_wars_matrix)
worldwide_vector

A New Hope The Empire Strikes Back      Return of the Jedi 
                775.398                 538.375                 475.106

In [6]:
# Star Wars box office in millions (!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)
star_wars_matrix <- rbind(new_hope, empire_strikes, return_jedi)
colnames(star_wars_matrix) <- c("US", "non-US")
rownames(star_wars_matrix) <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

# The worldwide box office figures
worldwide_vector <- rowSums(star_wars_matrix)

# Bind the new variable worldwide_vector as a column to star_wars_matrix: star_wars_ext
star_wars_ext = cbind(star_wars_matrix,worldwide_vector)
star_wars_ext

US      non-US worldwide_vector
A New Hope              460.998 314.4  775.398         
The Empire Strikes Back 290.475 247.9  538.375         
Return of the Jedi      309.306 165.8  475.106

In [7]:
phantom <- c(474.5,  552.5)
clones <- c(310.7,  338.7)
sith <- c(380.3,  468.5)

star_wars_matrix2 = rbind(phantom,clones,sith)
star_wars_matrix2

[,1]  [,2] 
phantom 474.5 552.5
clones  310.7 338.7
sith    380.3 468.5

In [8]:
colnames(star_wars_matrix2) <- c("US", "non-US")
rownames(star_wars_matrix2) <- c("The Phantom Menace","Attack of the Clones","Revenge of the Sith")
star_wars_matrix2

US    non-US
The Phantom Menace   474.5 552.5 
Attack of the Clones 310.7 338.7 
Revenge of the Sith  380.3 468.5

In [9]:
# Matrix that contains the first trilogy box office
star_wars_matrix  

# Matrix that contains the second trilogy box office
star_wars_matrix2 

# Combine both Star Wars trilogies in one matrix: all_wars_matrix
all_wars_matrix = rbind(star_wars_matrix,star_wars_matrix2)
all_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

US    non-US
The Phantom Menace   474.5 552.5 
Attack of the Clones 310.7 338.7 
Revenge of the Sith  380.3 468.5

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8 
The Phantom Menace      474.500 552.5 
Attack of the Clones    310.700 338.7 
Revenge of the Sith     380.300 468.5

In [10]:
# Print box office Star Wars
all_wars_matrix

# Total revenue for US and non-US: total_revenue_vector
total_revenue_vector=colSums(all_wars_matrix)
total_revenue_vector

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8 
The Phantom Menace      474.500 552.5 
Attack of the Clones    310.700 338.7 
Revenge of the Sith     380.300 468.5

US   non-US 
2226.279 2087.800

In [11]:
first_row <- c(6, 8, 7, 9, 9, 10)
second_row <- c(6, 8, 7, 5, 9,  6)
third_row <- c(5, 4, 6, 6, 7,  8)
fourth_row <- c(4, 5, 3, 4, 6,  8)

In [12]:
# Create the theater matrix
theater = rbind(first_row, second_row, third_row, fourth_row)
theater

[,1] [,2] [,3] [,4] [,5] [,6]
first_row  6    8    7    9    9    10  
second_row 6    8    7    5    9     6  
third_row  5    4    6    6    7     8  
fourth_row 4    5    3    4    6     8

In [13]:
# Calculate row_scores with rowSums()
row_scores = rowSums(theater)
row_scores

first_row second_row  third_row fourth_row 
        49         41         36         30

In [14]:
# cbind() together theater and row_scores: scores
scores = cbind(theater, row_scores)

scores

row_scores
first_row  6 8 7 9 9 10 49        
second_row 6 8 7 5 9  6 41        
third_row  5 4 6 6 7  8 36        
fourth_row 4 5 3 4 6  8 30

In [15]:
# star_wars_matrix is already defined in your workspace

# US box office revenue for "The Empire Strikes Back"
star_wars_matrix[2,1]

# non-US box office revenue for "A New Hope"
star_wars_matrix[1,2]

[1] 290.475

[1] 314.4

In [16]:
# star_wars_matrix is already defined in your workspace

# Select all US box office revenue
star_wars_matrix[,1]

# Select revenue for "A New Hope"
star_wars_matrix[1,]

# Average non-US revenue per movie: non_us_all
non_us_all=mean(star_wars_matrix[,2])
non_us_all
# Average non-US revenue of first two movies: non_us_some
non_us_some=mean(star_wars_matrix[1:2,2])
non_us_some

A New Hope The Empire Strikes Back      Return of the Jedi 
                460.998                 290.475                 309.306

US  non-US 
460.998 314.400

[1] 242.7

[1] 281.15

In [17]:
# star_wars_matrix is already defined in your workspace

# All figures for "A New Hope" and "Return of the Jedi"
star_wars_matrix[c(1,3),c(1,2)]

US      non-US
A New Hope         460.998 314.4 
Return of the Jedi 309.306 165.8

In [18]:
# star_wars_matrix is already defined in your workspace
star_wars_matrix
# Select the US revenues for "A New Hope" and "The Empire Strikes Back"
star_wars_matrix[c("A New Hope","The Empire Strikes Back"),1]

# Select the last two rows and both columns
star_wars_matrix[c(FALSE,TRUE,TRUE),]

# Select the non-US revenue for "The Empire Strikes Back"
star_wars_matrix[c("The Empire Strikes Back"),2]

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

A New Hope The Empire Strikes Back 
                460.998                 290.475

US      non-US
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

[1] 247.9

In [19]:
# A and D

In [20]:
view_count_1 <- c()

In [21]:
                        Mark Laurent Rachel Pierre
A New Hope                 1       3      2      3
The Empire Strikes Back    2       4      3      2
Return of the Jedi         1       3      2      1
The Phantom Menace         1       2      1      1
Attack of the Clones       1       1      0      1
Revenge of the Sith        0       1      0      0

ERROR: Error in parse(text = x, srcfile = src): <text>:1:30: unexpected symbol
1:                         Mark Laurent
                                 ^


In [ ]:
view_count_2

In [ ]:
                        Christel Walter Dave Monica
A New Hope                     2      1    5      0
The Empire Strikes Back        2      1    2      0
Return of the Jedi             2      0    3      0
The Phantom Menace             4      2    2      0
Attack of the Clones           5      3    2      0
Revenge of the Sith            4      1    3      1

In [ ]:
# Combine view_count_1 and view_count_2 in a new matrix: view_count_all
view_count_all <- cbind(view_count_1,view_count_2)
view_count_all

# Subset view counts for three loudest debaters: view_count_loud
view_count_loud = view_count_all[,c(3,6:7)]
view_count_loud
# Use colSums() to calculate the number of views: total_views_loud
total_views_loud = colSums(view_count_loud)
total_views_loud

In [22]:
# Star Wars box office in millions (!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)
star_wars_matrix <- rbind(new_hope, empire_strikes, return_jedi)
colnames(star_wars_matrix) <- c("US", "non-US")
rownames(star_wars_matrix) <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

# Estimation of visitors
visitors = star_wars_matrix / 5
  
# Print the estimate to the console
visitors

US      non-US
A New Hope              92.1996 62.88 
The Empire Strikes Back 58.0950 49.58 
Return of the Jedi      61.8612 33.16

In [24]:
# Star Wars box office in millions (!)
box_office_all <- c(461, 314.4, 290.5, 247.9, 309.3, 165.8)
movie_names <- c("A New Hope","The Empire Strikes Back","Return of the Jedi")
col_titles <- c("US","non-US")
star_wars_matrix <- matrix(box_office_all, nrow = 3, byrow = TRUE, dimnames = list(movie_names, col_titles))

# Definition of ticket_prices_matrix
ticket_prices_matrix <- matrix(c(5, 5, 6, 6, 7, 7), nrow = 3, byrow = TRUE, dimnames = list(movie_names, col_titles))
ticket_prices_matrix

US non-US
A New Hope              5  5     
The Empire Strikes Back 6  6     
Return of the Jedi      7  7

In [25]:
# Estimated number of visitors
visitors = star_wars_matrix / ticket_prices_matrix
visitors
# Average number of US visitors
average_us_visitors = mean(visitors[,1])
average_us_visitors
# Average number of non-US visitors
average_non_us_visitors = mean(visitors[,2])
average_non_us_visitors

US       non-US  
A New Hope              92.20000 62.88000
The Empire Strikes Back 48.41667 41.31667
Return of the Jedi      44.18571 23.68571

[1] 61.60079

[1] 42.62746

In [26]:
# Calculate the money that remains after subtracting the commission: remaining
remaining = star_wars_matrix - (star_wars_matrix * commission_rates)
remaining

# Calculate income per film: remaining_tot
remaining_tot = rowSums(remaining)
remaining_tot

# Calculate profit
profit = remaining_tot - budget
profit

ERROR: Error in eval(expr, envir, enclos): object 'commission_rates' not found


In [ ]:
commission_rates
                          US non-US
A New Hope              0.25   0.28
The Empire Strikes Back 0.23   0.26
Return of the Jedi      0.20   0.21